### ISSUE TITLE
Support more path functions on URLPath

### ISSUE THREAD

**Issue by uranusjr** [domdfcoding/apeye#37]
Currently, `URLPath.joinpath()` is explicitly overriden to not work. But the function is identical to `__div__`, and in some situations easier to use. For example, when chaning calls, the `/` operator requires additional parantheses, while a function call does not.

(Contrived example)

```pycon
>>> from apeye import URL
>>> url = URL("https://github.com/")
>>> (url.path / "uranusjr").with_name("domdfcoding")
>>> url.path.joinpath("uranusjr").with_name("domdfcoding")
```

The latter is slightly easier to read to me since I don’t need to backtrack and find the open paranthesis around `url.path / "uranusjr"`.

----

To be honest, everything except `as_uri` doesn’t really need to be disabled IMO. `relative_to()` seems especially useful, I can imagine doing something like `URL("https://github.com/uranusjr").path.relative_to(URL("https://github.com").path)`. Other methods/properties are arguably not useful, but it seems unnecessarily strict to me to disallow using them at all.

**Comment by domdfcoding** [comment]
Hi @uranusjr

Thanks for opening this issue. Sorry I've taken so long to get round to it.

I really don't remember why I made these raise `NotImplementedError`, but I can't see a reason why they shouldn't be implemented.

In #39 I have made every method except `as_uri` pass through to `PurePosixPath`, and I've also added the following methods to the `URL` class:

* `joinurl` (akin to `joinpath`)
* `relative_to` (like `URLPath.relative_to`, but less to type and handles a potential footgun with root URLs.
* `__lt__` etc. to allow sorting.


Your `relative_to` example can now be:

```python
>>> URL("https://github.com/uranusjr").relative_to(URL("https://github.com"))
URLPath("uranusjr")
```

And for `joinurl`:

```python
>>> url = URL("https://github.com/")
>>> url.joinurluranusjr").with_name("domdfcoding")
URL("https://github.com/domdfcoding")
```

-----

Thanks again for your suggestion.
