### ISSUE TITLE
Licensing Question GPL v3+ or LGPL V3+in file headers

### ISSUE THREAD

**Issue by SOesterreicher** [domdfcoding/apeye#60]
## Description

In the files I can see the following license information which puzzles me regarding the license to fulfill.
e.g. file: https://github.com/domdfcoding/apeye/blob/master/apeye/__init__.py
#
#  Copyright (c) 2020 Dominic Davis-Foster <dominic@davis-foster.co.uk>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the **GNU General Public License** as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

# this package
from apeye.url import URL, Domain, URLPath

__author__: str = "Dominic Davis-Foster"
__copyright__: str = "2020 Dominic Davis-Foster"
__license__: str = "**GNU Lesser General Public License v3 or later (LGPLv3+)**"
__version__: str = "1.2.0"
__email__: str = "dominic@davis-foster.co.uk"

==> Under which version are the files are handled GPL or LGPL ? Or can I choose? The main license in the root is LGPL V3+

## Steps to Reproduce

   1.
   2.
   3.

## Expected result:
One License or the possibility to choose.

## Version

  * Operating System:
  * Python:
  * apeye:

## Other Additional Information:

Is it possible to have one license listed in the files or add an information that the licenses can be chosen ?

**Comment by domdfcoding** [comment]
That looks to be a copy-paste error on my part. The references to the GPLv3 should be LGPLv3

(There's also the first few lines of the GPLv3 text that's used in `test_url.py` as a test, not as the license for that file).

I will correct the license in those files.

**Comment by SOesterreicher** [comment]
Thanks for the fast update.
Siegfried
